=== avodchyts/awinterlab/Task/resources/LandObjects.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="landtransport" type="landtransportType"/>
  <xs:complexType name="TruckType">
    <xs:sequence>
      <xs:element type="xs:string" name="typeVehicle"/>
      <xs:element name="valueVihicle">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="500"/>
            <xs:enumeration value="700"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="yearProduce"/>
      <xs:element name="fullWeight">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="40"/>
            <xs:enumeration value="60"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="QtyAxis">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="3"/>
            <xs:enumeration value="4"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="NameCar">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="DAF"/>
            <xs:enumeration value="Volvo"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>
  <xs:complexType name="TrucksType">
    <xs:sequence>
      <xs:element type="TruckType" name="Truck" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="landtransportType">
    <xs:sequence>
      <xs:element type="TrucksType" name="Trucks"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== avodchyts/awinterlab/Task/resources/LandObjects.xml
<?xml version="1.0" encoding="UTF-8"?>
<landtransport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="D:\InsCompany\src\resources\LandObjects.xsd ">
    <Trucks>
        <Truck name="DAF">
            <typeVehicle>Truck </typeVehicle>
            <valueVihicle>500</valueVihicle>
            <yearProduce> 2019</yearProduce>
            <fullWeight>40</fullWeight>
            <QtyAxis>3</QtyAxis>
            <NameCar>DAF</NameCar>
         </Truck>

        <Truck name="Volvo">
            <typeVehicle>Truck </typeVehicle>
            <valueVihicle>700</valueVihicle>
            <yearProduce> 2019</yearProduce>
            <fullWeight>60</fullWeight>
            <QtyAxis>4</QtyAxis>
            <NameCar>Volvo</NameCar>
        </Truck>

    </Trucks>
</landtransport>
