=== avodchyts/awinterlab/Task/resources/WaterObjects.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="watertransport" type="watertransportType"/>
  <xs:complexType name="ShipType">
    <xs:sequence>
      <xs:element type="xs:string" name="typeVehicle"/>
      <xs:element name="valueVihicle">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="100000"/>
            <xs:enumeration value="10000"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="yearProduce">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value=" 1909"/>
            <xs:enumeration value=" 2009"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="waterVolume">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="52310"/>
            <xs:enumeration value="5310"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="powerEngine">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="55000"/>
            <xs:enumeration value="5000"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="lengthBoat">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="269"/>
            <xs:enumeration value="29"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>
  <xs:complexType name="ShipsType">
    <xs:sequence>
      <xs:element type="ShipType" name="Ship" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="watertransportType">
    <xs:sequence>
      <xs:element type="ShipsType" name="Ships"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== avodchyts/awinterlab/Task/target/classes/WaterObjects.xml
<?xml version="1.0" encoding="UTF-8"?>
<watertransport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="D:\InsCompany\src\resources\WaterObjects.xsd ">
    <ships>
        <ship name="Titanic">
            <typeVehicle>Ship</typeVehicle>
            <valueVihicle>100000</valueVihicle>
            <yearProduce>1909</yearProduce>
            <waterVolume>52310</waterVolume>
            <powerEngine>55000</powerEngine>
            <lengthBoat>269</lengthBoat>
        </ship>

        <ship name="Dream">
            <typeVehicle>Ship</typeVehicle>
            <valueVihicle>10000</valueVihicle>
            <yearProduce>2009</yearProduce>
            <waterVolume>5310</waterVolume>
            <powerEngine>5000</powerEngine>
            <lengthBoat>29</lengthBoat>
        </ship>

    </ships>
</watertransport>
